version: "3.8"

services:
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .devcontainer/credentials.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Let the container shell expand $POSTGRES_USER/$POSTGRES_DB
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .devcontainer/credentials.env
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - N8N_BASIC_AUTH_ACTIVE=true
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  n8n_data:
